version: '3.9'

services:
  backend:
    build: ./backend
    container_name: smart-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: smart-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: smartdb
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n
    container_name: smart-n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Santiago
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - ./n8n:/home/node/.n8n
    depends_on:
      - backend

volumes:
  postgres_data:
